apiVersion: apps/v1
kind:  Deployment
metadata:
  name: host-path
spec:
  replicas: 4
  #minReadySeconds: 56
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: nginx
      role: front-end    
  template:
    metadata:
      labels:
        app: nginx
        role: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 9080
          resources:
              limits:
                cpu: "100m"
                memory: "100Mi"
          volumeMounts:
            - mountPath: /test-mnt
              name: test-volume 
          readOnly: false             
      volumes:
        - name: test-volume
          hostPath:
              path: /test-volume
              type: DirectoryOrCreate              
