apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    app: websphare
  template:
    metadata:
      name: websphare
      labels:
        app: websphare
    spec:
      containers:
        - name: websphare
          image: valunaik/websphare
          ports:
            - containerPort: 9080
