apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
    role: front-end 
  type: LoadBalancer
  ports:
  - nodePort: 32000
    port: 80
    targetPort: 80
    protocol: TCP
